AllCops:
  Exclude:
    - 'bin/*'
    - 'db/**/*'
    - 'script/**/*'
    - 'Guardfile'
    - 'Rakefile'
Documentation:
  Enabled: false
Metrics/LineLength:
  Enabled: true
  Exclude:
    - 'config/**/*'
Rails/TimeZone:
  Enabled: false
SignalException:
  Enabled: false
Style/PredicateName:
  NamePrefix:
    - is_
    - have_
  NamePrefixBlacklist:
    - is_
    - have_
Style/StringLiterals:
  EnforcedStyle: double_quotes
Style/TrailingComma:
  EnforcedStyleForMultiline: comma
  Enabled: true
