require "airbrussh/capistrano"
require "capistrano/deploy"
require "capistrano/passenger"
require "capistrano/rails"
require "capistrano/setup"
require "rvm1/capistrano3"
require "whenever/capistrano"
